# Generated by Django 2.2.7 on 2020-03-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarddata',
            name='specific_id',
        ),
    ]
