# Generated by Django 2.2.7 on 2020-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0002_remove_boarddata_specific_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='symptom',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
