# Generated by Django 2.2.7 on 2020-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0003_boarddata_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='specific_id',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
