# Generated by Django 2.2.7 on 2020-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0004_boarddata_specific_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddata',
            name='symptom',
            field=models.CharField(max_length=30),
        ),
    ]
