# Generated by Django 2.2.7 on 2020-03-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0006_auto_20200305_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardData',
        ),
    ]
